# Generated by Django 5.2.4 on 2025-12-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('main', 'Main Branch'), ('sub', 'Sub Branch')], default='sub', max_length=10),
        ),
    ]
