# Generated by Django 5.2.4 on 2025-11-28 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_property_sales', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='propertysale',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
