# Generated by Django 5.2.4 on 2025-12-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0002_propertysale_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretary', 'Secretary'), ('super_admin', 'Super Admin'), ('branch_admin', 'Branch Admin')], default='admin', max_length=20),
        ),
    ]
