# Generated by Django 5.2.4 on 2025-12-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0003_user_phone_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretary', 'Secretary'), ('chief_accountant', 'Chief Accountant'), ('branch_admin', 'Branch Admin')], default='admin', max_length=20),
        ),
    ]
