# Generated by Django 5.2.4 on 2025-12-24 03:46

from django.db import migrations

def migrate_super_admin_to_chief_accountant(apps, schema_editor):
    User = apps.get_model('tripled', 'User')
    # Update all users with 'super_admin' type to 'chief_accountant'
    count = User.objects.filter(user_type='super_admin').update(user_type='chief_accountant')
    print(f"\nMigrated {count} users from super_admin to chief_accountant")

def reverse_migration(apps, schema_editor):
    User = apps.get_model('tripled', 'User')
    # Revert 'chief_accountant' back to 'super_admin'
    # Note: This might revert newly created chief accountants too, but it is necessary for reversibility
    User.objects.filter(user_type='chief_accountant').update(user_type='super_admin')

class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.RunPython(migrate_super_admin_to_chief_accountant, reverse_migration),
    ]
