# Generated by Django 5.2.4 on 2025-12-28 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0005_auto_20251224_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('is_taken', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='tripled.property')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('property', 'number')},
            },
        ),
        migrations.AddField(
            model_name='propertysale',
            name='plots',
            field=models.ManyToManyField(blank=True, related_name='sales', to='tripled.plot'),
        ),
    ]
