# Generated by Django 5.2.4 on 2025-12-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0006_plot_propertysale_plots'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
    ]
