# Generated by Django 5.2.4 on 2025-12-30 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0008_downloadableform_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='exact_location',
            field=models.CharField(blank=True, help_text='Specific location or address for display', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Show this property on the public website'),
        ),
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main image displayed on the website', null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_landmarks',
            field=models.TextField(blank=True, help_text='Key landmarks near the property', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_size',
            field=models.CharField(blank=True, help_text='Size of the plots (e.g. 500sqm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to YouTube/Vimeo video tour', null=True),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tripled.property')),
            ],
        ),
    ]
