# Generated by Django 5.2.4 on 2025-12-30 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0009_property_exact_location_property_is_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'FCT')], max_length=100)),
                ('exact_location', models.CharField(help_text='Specific location or address for display', max_length=255)),
                ('nearby_landmarks', models.TextField(blank=True, help_text='Key landmarks near the property', null=True)),
                ('plot_size', models.CharField(blank=True, max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Link to YouTube/Vimeo video tour', null=True)),
                ('main_image', models.ImageField(help_text='Main image displayed on the website', upload_to='website_properties/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('is_visible', models.BooleanField(default=True, help_text='Show this property on the public website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Website Properties',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='exact_location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='property',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='nearby_landmarks',
        ),
        migrations.RemoveField(
            model_name='property',
            name='plot_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video_url',
        ),
        migrations.CreateModel(
            name='WebsitePropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website_properties/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tripled.websiteproperty')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
