# Generated by Django 5.2.4 on 2025-12-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripled', '0010_websiteproperty_remove_property_exact_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full Facebook Page URL', null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Full Instagram Profile URL', null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp Number (e.g., +234...)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='company_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='company_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='company_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
